[package]
name = "rust-model-viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.19.0", features = ["jpeg", "bevy_dev_tools"] }
bevy_obj = "0.19.0"
bevy_panorbit_camera = "0.35.0"
rfd = "0.17.2"
stl_io = "0.11.0"
threemf = { version = "0.8.0", optional = true }

[features]
default = []
three-mf = ["dep:threemf"]
